using System.CommandLine;
using Umbraco.Cli.Infrastructure;

namespace Umbraco.Cli.Tests;

/// <summary>
/// Tests for the machine-readable command catalog (#60): reflecting over a
/// <see cref="System.CommandLine"/> tree yields a faithful, JSON-serializable description of
/// every command, argument, and option.
/// </summary>
public class CommandCatalogTests
{
    private static RootCommand BuildSampleTree()
    {
        var root = new RootCommand("root help");
        // A recursive global option lives on the root only.
        root.Add(new Option<string>("--output") { Recursive = true, Description = "format" });

        var noun = new Command("content", "manage content");
        var verb = new Command("delete", "remove an item");
        verb.Add(new Argument<Guid>("id") { Description = "the id" });
        verb.Add(new Option<bool>("--yes", new[] { "-y" }) { Description = "skip prompt" });
        verb.Destructive(_ => "Delete it?");
        var create = new Command("create").Mutating();
        create.Add(new Option<string>("--name") { Required = true });
        create.Add(new Option<string[]>("--tags"));
        noun.Add(verb);
        noun.Add(create);
        root.Add(noun);
        return root;
    }

    [Fact]
    public void Describe_CapturesNestedCommandsArgumentsAndOptions()
    {
        var catalog = CommandCatalog.Describe(BuildSampleTree());

        // Global option is described once, on the root.
        Assert.Contains(catalog.Options, o => o.Name == "--output");

        var content = Assert.Single(catalog.Commands, c => c.Name == "content");
        Assert.Equal("manage content", content.Description);

        var delete = Assert.Single(content.Commands, c => c.Name == "delete");
        var idArg = Assert.Single(delete.Arguments);
        Assert.Equal("id", idArg.Name);
        Assert.Equal("guid", idArg.Type);
        Assert.True(idArg.Required);

        var yes = Assert.Single(delete.Options, o => o.Name == "--yes");
        Assert.Equal("flag", yes.Type); // a boolean switch
        Assert.Contains("-y", yes.Aliases);
    }

    [Fact]
    public void Describe_MarksRequiredOptionsAndFriendlyArrayType()
    {
        var catalog = CommandCatalog.Describe(BuildSampleTree());
        var create = catalog
            .Commands.Single(c => c.Name == "content")
            .Commands.Single(c => c.Name == "create");

        var name = Assert.Single(create.Options, o => o.Name == "--name");
        Assert.True(name.Required);
        Assert.Equal("string", name.Type);

        var tags = Assert.Single(create.Options, o => o.Name == "--tags");
        Assert.False(tags.Required);
        Assert.Equal("string[]", tags.Type); // multi-valued renders friendly
    }

    [Fact]
    public void Describe_ExcludesAutogeneratedHelpOption()
    {
        // The auto --help option is noise in the catalog and must be filtered out.
        var catalog = CommandCatalog.Describe(BuildSampleTree());

        Assert.DoesNotContain(catalog.Options, o => o.Name == "--help");
    }

    [Fact]
    public void Describe_ExcludesAutogeneratedVersionOption()
    {
        // A RootCommand auto-adds --version; it must be filtered out of the catalog too.
        var catalog = CommandCatalog.Describe(new RootCommand());

        Assert.DoesNotContain(catalog.Options, o => o.Name == "--version");
    }

    [Fact]
    public void Describe_RootNameIsStable()
    {
        // The root name must not be the environment-dependent executable name.
        Assert.Equal("umbraco", CommandCatalog.Describe(new RootCommand()).Name);
    }

    [Fact]
    public void Describe_UnwrapsNullableValueType()
    {
        var root = new RootCommand();
        var noun = new Command("x");
        noun.Add(new Option<Guid?>("--parent"));
        root.Add(noun);

        var parent = CommandCatalog
            .Describe(root)
            .Commands.Single(c => c.Name == "x")
            .Options.Single(o => o.Name == "--parent");

        Assert.Equal("guid", parent.Type); // Guid? unwraps to guid
    }

    [Fact]
    public void Describe_MarksDestructiveAndMutatingLeafVerbs()
    {
        // #84: a leaf `delete` verb is both mutating and destructive; a `create` verb is
        // mutating but not destructive; the grouping noun is neither.
        var catalog = CommandCatalog.Describe(BuildSampleTree());
        var content = catalog.Commands.Single(c => c.Name == "content");
        var delete = content.Commands.Single(c => c.Name == "delete");
        var create = content.Commands.Single(c => c.Name == "create");

        Assert.True(delete.Mutating);
        Assert.True(delete.Destructive);
        Assert.True(create.Mutating);
        Assert.False(create.Destructive); // reversible-ish create is not destructive
        Assert.False(content.Mutating); // the noun groups verbs; it does not run
        Assert.False(content.Destructive);
    }

    [Fact]
    public void Describe_DeclaredDestructiveCommand_IsMutatingWhateverItsVerb()
    {
        // #84: Destructive ⊆ Mutating, so an agent that gates writes on `mutating` never misses
        // a gated one. Since #255 that holds for any declared command, not a list of verbs.
        var root = new RootCommand();
        root.Add(new Command("regenerate").Destructive(_ => "Regenerate?"));

        var node = Assert.Single(CommandCatalog.Describe(root).Commands);

        Assert.True(node.Destructive);
        Assert.True(node.Mutating);
    }

    [Fact]
    public void Describe_UndeclaredDeleteVerb_IsNotDestructive()
    {
        // #255: the catalog follows the declaration the executor gates on, not the verb name,
        // so a command that is not gated is never reported as needing --yes.
        var root = new RootCommand();
        root.Add(new Command("delete"));

        Assert.False(Assert.Single(CommandCatalog.Describe(root).Commands).Destructive);
    }

    [Fact]
    public void Describe_ConditionallyDestructiveCommand_NamesTheOption()
    {
        // `apply` is only destructive with --prune: reporting destructive: true would say every
        // apply needs --yes, which is untrue.
        var root = new RootCommand();
        root.Add(new Command("apply").DestructiveWith(new Option<bool>("--prune"), _ => "Prune?"));

        var node = Assert.Single(CommandCatalog.Describe(root).Commands);

        Assert.False(node.Destructive);
        Assert.Equal("--prune", node.DestructiveWhen);
        Assert.True(node.Mutating);
    }

    [Fact]
    public void Describe_Publish_IsMutatingButNotGated()
    {
        // #82: publishing is additive/low-impact, so it stays mutating-but-not-gated — the
        // catalog must not tell agents that `publish` needs --yes.
        var root = new RootCommand();
        root.Add(new Command("publish").Mutating());

        var publish = CommandCatalog.Describe(root).Commands.Single(c => c.Name == "publish");
        Assert.True(publish.Mutating);
        Assert.False(publish.Destructive);
    }

    [Fact]
    public void Describe_OptionWithDefault_HasDefaultTrue()
    {
        // #84: an option with a default factory is flagged HasDefault so an agent knows it is
        // safe to omit.
        var root = new RootCommand();
        var noun = new Command("x");
        noun.Add(new Option<int>("--take") { DefaultValueFactory = _ => 20 });
        noun.Add(new Option<string>("--name")); // no default
        root.Add(noun);

        var opts = CommandCatalog.Describe(root).Commands.Single(c => c.Name == "x").Options;
        Assert.True(opts.Single(o => o.Name == "--take").HasDefault);
        Assert.False(opts.Single(o => o.Name == "--name").HasDefault);
    }

    [Fact]
    public void Describe_AcceptsJsonBody_WhenJsonBodyOptionPresent()
    {
        // #84: a command exposing --json-body is flagged, explaining why its field options are
        // reported required:false (they are alternatives to the body).
        var root = new RootCommand();
        var noun = new Command("content");
        var create = new Command("create");
        create.Add(new Option<FileInfo?>("--json-body"));
        noun.Add(create);
        root.Add(noun);

        var createNode = CommandCatalog
            .Describe(root)
            .Commands.Single(c => c.Name == "content")
            .Commands.Single(c => c.Name == "create");
        Assert.True(createNode.AcceptsJsonBody);
    }

    /// <summary>
    /// Verbs that always send a write. The catalog no longer infers anything from them (#258);
    /// this list only lets the guard below catch a new write command that forgot to declare it.
    /// </summary>
    private static readonly HashSet<string> WriteVerbs =
    [
        "create",
        "update",
        "delete",
        "publish",
        "unpublish",
        "upload",
        "move",
        "copy",
        "trash",
        "restore",
        "rollback",
        "empty-recycle-bin",
        "publish-descendants",
        "invite",
        "apply",
        "enable",
        "disable",
        "build",
        "rebuild",
        "sort",
        "set",
        "add-users",
        "remove-users",
    ];

    [Fact]
    public void Describe_EveryShippedLeafWithAWriteVerb_IsDeclaredMutating()
    {
        // #258: mutating comes only from each command's declaration, so a write command that
        // forgets .Mutating() would be reported as a safe read. Catch it here.
        var undeclared = Leaves(CommandCatalog.Describe(TestCliRoot.Build()), "")
            .Where(l => WriteVerbs.Contains(l.Node.Name) && !l.Node.Mutating)
            .Select(l => l.Path)
            .ToList();

        Assert.True(undeclared.Count == 0, "Undeclared writes: " + string.Join(", ", undeclared));
    }

    /// <summary>Every leaf under <paramref name="node"/>, with its space-separated path.</summary>
    private static IEnumerable<(string Path, CommandCatalogNode Node)> Leaves(
        CommandCatalogNode node,
        string path
    ) =>
        node.Commands.Count == 0
            ? [(path.Trim(), node)]
            : node.Commands.SelectMany(c => Leaves(c, $"{path} {c.Name}"));

    [Fact]
    public void Describe_UnknownVerbDeclaredMutating_IsMutating()
    {
        // A write under a verb outside the standard set (e.g. `sort`, a PUT) is only reported
        // mutating because the command declares it.
        var root = new RootCommand();
        root.Add(new Command("reorder").Mutating());

        var node = CommandCatalog.Describe(root).Commands.Single();

        Assert.True(node.Mutating);
    }

    [Fact]
    public void Describe_UnknownVerbNotDeclared_IsNotMutating()
    {
        var root = new RootCommand();
        root.Add(new Command("reorder"));

        var node = CommandCatalog.Describe(root).Commands.Single();

        Assert.False(node.Mutating);
    }

    [Theory]
    [InlineData("content", "sort")]
    [InlineData("media", "sort")]
    [InlineData("content", "domain", "set")]
    [InlineData("document-blueprint", "from-document")]
    [InlineData("health", "run")]
    public void Describe_ShippedWritesWithNonStandardVerbs_AreMutating(params string[] path)
    {
        // These send PUT/POST under verbs the verb set does not know, and were reported as safe
        // reads until they declared themselves.
        var node = CommandCatalog.Describe(TestCliRoot.Build());
        foreach (var name in path)
            node = node.Commands.Single(c => c.Name == name);

        Assert.True(node.Mutating);
    }

    [Fact]
    public void Describe_ArgumentWithDefault_IsNotRequired()
    {
        // An argument that has a default parses fine when omitted, so it is not "required"
        // even though its arity lower-bound is 1.
        var root = new RootCommand();
        var noun = new Command("x");
        noun.Add(new Argument<string>("val") { DefaultValueFactory = _ => "d" });
        root.Add(noun);

        var arg = CommandCatalog
            .Describe(root)
            .Commands.Single(c => c.Name == "x")
            .Arguments.Single();

        Assert.False(arg.Required);
    }
}
