using System.CommandLine;
using Umbraco.Cli.Infrastructure;

namespace Umbraco.Cli.Tests;

/// <summary>
/// Tests for the machine-readable command catalog (#60): reflecting over a
/// <see cref="System.CommandLine"/> tree yields a faithful, JSON-serializable description of
/// every command, argument, and option.
/// </summary>
public class CommandCatalogTests
{
    private static RootCommand BuildSampleTree()
    {
        var root = new RootCommand("root help");
        // A recursive global option lives on the root only.
        root.Add(new Option<string>("--output") { Recursive = true, Description = "format" });

        var noun = new Command("content", "manage content");
        var verb = new Command("delete", "remove an item");
        verb.Add(new Argument<Guid>("id") { Description = "the id" });
        verb.Add(new Option<bool>("--yes", new[] { "-y" }) { Description = "skip prompt" });
        var create = new Command("create");
        create.Add(new Option<string>("--name") { Required = true });
        create.Add(new Option<string[]>("--tags"));
        noun.Add(verb);
        noun.Add(create);
        root.Add(noun);
        return root;
    }

    [Fact]
    public void Describe_CapturesNestedCommandsArgumentsAndOptions()
    {
        var catalog = CommandCatalog.Describe(BuildSampleTree());

        // Global option is described once, on the root.
        Assert.Contains(catalog.Options, o => o.Name == "--output");

        var content = Assert.Single(catalog.Commands, c => c.Name == "content");
        Assert.Equal("manage content", content.Description);

        var delete = Assert.Single(content.Commands, c => c.Name == "delete");
        var idArg = Assert.Single(delete.Arguments);
        Assert.Equal("id", idArg.Name);
        Assert.Equal("guid", idArg.Type);
        Assert.True(idArg.Required);

        var yes = Assert.Single(delete.Options, o => o.Name == "--yes");
        Assert.Equal("flag", yes.Type); // a boolean switch
        Assert.Contains("-y", yes.Aliases);
    }

    [Fact]
    public void Describe_MarksRequiredOptionsAndFriendlyArrayType()
    {
        var catalog = CommandCatalog.Describe(BuildSampleTree());
        var create = catalog
            .Commands.Single(c => c.Name == "content")
            .Commands.Single(c => c.Name == "create");

        var name = Assert.Single(create.Options, o => o.Name == "--name");
        Assert.True(name.Required);
        Assert.Equal("string", name.Type);

        var tags = Assert.Single(create.Options, o => o.Name == "--tags");
        Assert.False(tags.Required);
        Assert.Equal("string[]", tags.Type); // multi-valued renders friendly
    }

    [Fact]
    public void Describe_ExcludesAutogeneratedHelpOption()
    {
        // The auto --help option is noise in the catalog and must be filtered out.
        var catalog = CommandCatalog.Describe(BuildSampleTree());

        Assert.DoesNotContain(catalog.Options, o => o.Name == "--help");
    }
}
