"""perf_report.py - render docs/performance.md from bench.py's results.

Run it through bench.py, from anywhere:

  python3 tests/hands-on/bench.py report

It reads every docs/performance/results/*.json that bench.py wrote (tests/hands-on/README.md, "Benchmarks",
documents the schema) and writes docs/performance.md whole: an at-a-glance comparison of the published CLI
versions, one table per Umbraco version and machine, with one column per scenario. Each cell is the median
end-to-end time of the newest direct run of that version and scenario: the median, because on a working machine
one slow run in ten moves the mean more than the difference between versions. Builds packed from a checkout (`--cli local`) and runs through the
latency proxy (`--latency`) stay in the results files but are not on the page: it compares releases.

How the numbers are measured, and how to read them, is hand-written in docs/performance-testing.md. Every number
on the generated page comes from a results file: to change the text, edit it here and regenerate; to change a
number, record a new run. The output depends only on the results files and bench.py's scenario table, so running
it again changes nothing, and it is ASCII only. It stops before writing anything when there are no results
files, or a file can't be read or has another schemaVersion.
"""
import argparse
import json
import re
import textwrap
import unicodedata

import harness
from harness import ROOT, die, say

REPO = ROOT.parent.parent
RESULTS = REPO / "docs" / "performance" / "results"
PAGE = REPO / "docs" / "performance.md"
SCHEMA_VERSION = 1  # the results schema this report reads: bench.py's SCHEMA_VERSION
BENCH = "python3 tests/hands-on/bench.py"
WIDTH = 110  # prose line length in the generated markdown

# Column headings for bench.py's scenarios. A scenario missing here is headed by its name.
LABELS = {"version": "Startup", "get": "Read one item", "list": "List data types",
          "content-export": "Export content", "schema-diff": "Diff schema"}

# Punctuation the results could carry (in a CPU or OS name, or a note), and its ASCII spelling.
ASCII = {"–": "-", "—": "-", "‘": "'", "’": "'", "“": '"', "”": '"', "…": "...",
         "×": "x", " ": " ", "®": "(R)", "™": "(TM)"}

GENERATED = ("<!-- Generated by `python3 tests/hands-on/bench.py report` from docs/performance/results/. Don't edit "
             "this file: record a new run with bench.py, or change the text in tests/hands-on/tools/perf_report.py, "
             "then regenerate. -->")


# ---------------------------------------------------------------- input ------
def rel(path):
    """A path as messages show it: relative to the repository when it is inside it.

    :param path: an absolute path.
    :returns: the path, with forward slashes.
    """
    return path.relative_to(REPO).as_posix() if path.is_relative_to(REPO) else path.as_posix()


def load_results(folder):
    """Read every results file in a folder, oldest run first.

    :param folder: the results folder (docs/performance/results).
    :returns: a list of `(stem, doc)` pairs, ordered by each run's start and then its file name.
    :raises SystemExit: when there are no results files, or one can't be read or has another schemaVersion.
    """
    files = sorted(folder.glob("*.json")) if folder.is_dir() else []
    if not files:
        die(f"No results files in {rel(folder)}/, so there is nothing to report. Record a run first, for example:\n"
            f"  {BENCH} --cli local --umbraco 17\nNothing was written.")
    runs = []
    for path in files:
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as e:
            die(f"Can't read {rel(path)}: {e}. Nothing was written.")
        if not isinstance(doc, dict) or doc.get("schemaVersion") != SCHEMA_VERSION:
            found = doc.get("schemaVersion") if isinstance(doc, dict) else None
            die(f"{rel(path)} has schemaVersion {found!r}, and this report reads {SCHEMA_VERSION} only. Update "
                "tests/hands-on/tools/perf_report.py for the new schema. Nothing was written.")
        runs.append((path.stem, doc))
    return sorted(runs, key=lambda run: (run[1]["date"], run[0]))


def latency(row):
    """The latency a result was timed through (`bench.py --latency`): 0 for a direct run.

    Files written before the field existed hold direct runs only, so a missing field is 0.

    :param row: a results row.
    :returns: the added milliseconds per request.
    """
    return row.get("latencyMs") or 0


def is_local(cli):
    """Whether a result's CLI build was packed from a checkout (`--cli local`) rather than published.

    :param cli: a results row's `cli`.
    :returns: True for a local build.
    """
    return cli["label"] == "local"


def published(runs):
    """Group the newest direct result of every published build by Umbraco version and machine.

    Runs are read oldest first, so a newer run of the same build, scenario, Umbraco version and machine replaces
    an older one. Local builds and latency runs are left out.

    :param runs: every `(stem, doc)`, oldest first.
    :returns: `{(umbraco, machine label): {"cells": {(cli version, scenario): row}, "docs": {stem: doc}}}`,
        where `docs` holds the runs a group's cells came from.
    """
    groups = {}
    for stem, doc in runs:
        for row in doc["results"]:
            if latency(row) or is_local(row["cli"]):
                continue
            group = groups.setdefault((row["umbraco"], doc["machine"]["label"]), {"cells": {}, "sources": {}})
            group["cells"][(row["cli"]["version"], row["scenario"])] = row
            group["sources"][(row["cli"]["version"], row["scenario"])] = (stem, doc)
    for group in groups.values():
        group["docs"] = dict(group.pop("sources").values())
    return groups


# ---------------------------------------------------------------- text -------
def display_command(command):
    """A command as the docs show it, for reading rather than pasting.

    Drops the options every API scenario passes for isolation (`--output json --config {config}`), shows the
    scratch output file as `<file>` and the fixtures folder as its repository path, and any other placeholder
    (a fixture id such as `{home}`) as `<home>`.

    :param command: a scenario's argv joined after `umbraco`.
    :returns: the command.
    """
    text = re.sub(r"\s--output\s+json\b|\s--config\s+\{config\}", "", command)
    text = re.sub(r"\{work\}/\S+", "<file>", text).replace("{fixtures}", "tests/hands-on/fixtures")
    return re.sub(r"\{(\w+)\}", r"<\1>", text)


def cell(row):
    """One version's time for one scenario.

    :param row: the results row, or None when that version wasn't timed on that scenario.
    :returns: the end-to-end median in whole milliseconds; "-" for a failed run; "" when not timed.
    """
    if row is None:
        return ""
    return "-" if row["status"] != "ok" else f"{row['endToEndMs']['median']:.0f}"


def para(text):
    """One paragraph of prose, wrapped at WIDTH.

    :param text: the paragraph, with any spacing.
    :returns: the wrapped paragraph.
    """
    return "\n".join(textwrap.wrap(" ".join(text.split()), WIDTH, break_long_words=False, break_on_hyphens=False))


def table(headers, align, rows):
    """A markdown table.

    :param headers: the column headings.
    :param align: "l" or "r" per column.
    :param rows: lists of cell text. A `|` or line break in a cell is replaced, so the cell stays one cell.
    :returns: the table.
    """
    def clean(text):
        return " ".join(str(text).split()).replace("|", "/")
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" if a == "l" else "--:" for a in align) + "|"]
    return "\n".join(lines + ["| " + " | ".join(clean(c) for c in row) + " |" for row in rows])


def ascii_only(text):
    """Text with only ASCII characters: known punctuation spelled out, accents dropped, anything else as "?".

    :param text: the generated markdown.
    :returns: the same text in ASCII.
    """
    text = unicodedata.normalize("NFKD", "".join(ASCII.get(c, c) for c in text))
    return "".join(c for c in text if not unicodedata.combining(c)).encode("ascii", "replace").decode("ascii")


# ---------------------------------------------------------------- page -------
def group_section(umbraco, machine, group, order, name_machine):
    """One table: every published version measured on one Umbraco version and machine, a column per scenario.

    :param umbraco: the exact Umbraco version.
    :param machine: the machine label.
    :param group: the group `published` built for them.
    :param order: scenario names in bench.py's order.
    :param name_machine: whether the heading names the machine (only when results come from more than one).
    :returns: the markdown.
    """
    cells, docs = group["cells"], group["docs"]
    versions = sorted({v for v, _ in cells}, key=harness.version_key)
    scenarios = [s for s in order if any(s == name for _, name in cells)]
    scenarios += sorted({name for _, name in cells} - set(scenarios))  # scenarios bench.py no longer has, last
    rows = [[v, *(cell(cells.get((v, s))) for s in scenarios)] for v in versions]

    newest = max(docs.values(), key=lambda doc: doc["date"])
    m = newest["machine"]
    dates = sorted({doc["date"][:10] for doc in docs.values()})
    counts = sorted({doc["hyperfine"]["runs"] for doc in docs.values()})
    stamp = (f"Measured {' to '.join(dict.fromkeys([dates[0], dates[-1]]))} on {m['cpu']} ({m['logicalCores']} "
             f"logical cores), {m['os']}. Each time is the median of {' to '.join(map(str, dict.fromkeys([counts[0], counts[-1]])))} "
             "runs.")
    notes = [f"Note ({doc['date'][:10]}): {doc['note']}" for _, doc in sorted(docs.items()) if doc.get("note")]
    parts = [f"## Umbraco {umbraco}" + (f", {machine}" if name_machine else ""),
             table(["CLI", *(LABELS.get(s, s) for s in scenarios)], "l" + "r" * len(scenarios), rows)]
    if any("-" in row[1:] for row in rows):
        parts.append(para("`-` means that version couldn't run the command, usually because it doesn't have it yet."))
    parts += [para(stamp), *(para(n) for n in notes)]
    return "\n\n".join(parts)


def render_page(runs, scenarios):
    """docs/performance.md, whole.

    :param runs: every `(stem, doc)`, oldest first.
    :param scenarios: bench.py's SCENARIOS: the column order, and what each column runs.
    :returns: the markdown.
    """
    order = [s.name for s in scenarios]
    groups = published(runs)
    name_machine = len({machine for _, machine in groups}) > 1
    # Newest Umbraco first, then by machine.
    keys = sorted(groups, key=lambda k: (harness.version_key(k[0]), k[1]), reverse=True)
    shown = {name for g in groups.values() for _, name in g["cells"]}

    parts = [
        "# Performance",
        GENERATED,
        para("How long common commands take in each released version of the CLI. Times are the median end-to-end "
             "time, in milliseconds, against a local Umbraco site with a small set of test content, so they include "
             "Umbraco's own time. Lower is better. Compare rows within one table: each table is one Umbraco "
             "version on one machine."),
    ]
    if keys:
        parts += [group_section(u, m, groups[(u, m)], order, name_machine) for u, m in keys]
        parts += ["## What each column runs",
                  table(["Column", "Command"], "ll",
                        [[LABELS.get(s.name, s.name), f"`{display_command(' '.join(['umbraco', *s.argv]))}`"]
                         for s in scenarios if s.name in shown])]
    else:
        parts.append(para("No released version has been measured yet."))
    parts.append(para("How these numbers are measured, how to read them, and how to add a run: "
                      "[Performance testing](performance-testing.md)."))
    return "\n\n".join(parts) + "\n"


# ---------------------------------------------------------------- output -----
def read_raw(path):
    """A file's text exactly as it is on disk, line endings included.

    :param path: the file.
    :returns: the text, or None when there is no file.
    """
    if not path.is_file():
        return None
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def write(path, old, new):
    """Write a file only when its text changes.

    :param path: the file.
    :param old: its current text (None when it doesn't exist).
    :param new: the text it should have.
    :returns: whether the file was written.
    """
    if old == new:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(new)
    return True


def main(argv, scenarios):
    """Regenerate docs/performance.md (`bench.py report`).

    :param argv: the arguments after `report`.
    :param scenarios: bench.py's SCENARIOS: the column order, and what each column runs.
    :raises SystemExit: as the module docstring says, before anything is written.
    """
    argparse.ArgumentParser(prog="bench.py report", description=__doc__,
                            formatter_class=argparse.RawDescriptionHelpFormatter).parse_args(argv)
    runs = load_results(RESULTS)
    old = read_raw(PAGE)
    newline = "\r\n" if old and "\r\n" in old else "\n"  # keep the checkout's line endings
    new = ascii_only(render_page(runs, scenarios)).replace("\n", newline)
    say(f"{rel(PAGE)}: {'updated' if write(PAGE, old, new) else 'unchanged'}")
    print(f"    from {len(runs)} results file(s)")
