"""perf_report.py - render the README's Performance section and docs/performance.md from bench.py's results.

Run it through bench.py, from anywhere:

  python3 tests/hands-on/bench.py report

It reads every docs/performance/results/*.json that bench.py wrote (tests/hands-on/README.md, "Benchmarks",
documents the schema), then:

- rewrites only the lines between `<!-- perf:start -->` and `<!-- perf:end -->` in the repository's README.md:
  a headline table (startup, one `get`, one large export, each with its request count) for the newest published
  CLI build on the newest Umbraco version in the newest results file, stamped with the machine, versions and
  date. A `local` build is quoted only when that file has no published one, because readers install published
  builds;
- writes docs/performance.md whole: the method, every run, history per scenario across CLI builds, the Umbraco
  version comparison, how to reproduce every number, and the caveats.

All the prose on both pages lives in this file, and every number comes from a results file: to change the text,
edit it here and regenerate; to change a number, record a new run. The output depends only on the results files
and bench.py's scenario table, so running it again changes nothing, and it is ASCII only. It stops before
writing anything when there are no results files, a file can't be read or has another schemaVersion, or
README.md doesn't hold exactly one pair of markers.
"""
import argparse
import json
import re
import textwrap
import unicodedata

import harness
from harness import ROOT, die, say

REPO = ROOT.parent.parent
RESULTS = REPO / "docs" / "performance" / "results"
README = REPO / "README.md"
PAGE = REPO / "docs" / "performance.md"
START, END = "<!-- perf:start -->", "<!-- perf:end -->"
SCHEMA_VERSION = 1  # the results schema this report reads: bench.py's SCHEMA_VERSION
GITHUB = "https://github.com/worm-brain/Umbraco.Cli"
BENCH = "python3 tests/hands-on/bench.py"
WIDTH = 110  # prose line length in the generated markdown

# What the README quotes, in order: (scenario, what it shows). Startup, one item, and one large export.
HEADLINE = [("version", "Startup"), ("get", "Read one item"), ("content-export", "Export the content tree")]

# Punctuation the results could carry (in a CPU or OS name, or a CLI error), and its ASCII spelling.
ASCII = {"–": "-", "—": "-", "‘": "'", "’": "'", "“": '"', "”": '"', "…": "...",
         "×": "x", " ": " ", "®": "(R)", "™": "(TM)"}

# A line that markdown would read as the start of a list, quote, table, heading or setext underline.
BLOCK_START = re.compile(r"([-+*>|#]|\d+[.)])(\s|$)|(-+|=+)$")

GENERATED = ("<!-- Generated by `python3 tests/hands-on/bench.py report` from docs/performance/results/. Don't edit "
             "{what}: record a new run with bench.py, or change the text in tests/hands-on/tools/perf_report.py, "
             "then regenerate. -->")


# ---------------------------------------------------------------- input ------
def rel(path):
    """A path as messages show it: relative to the repository when it is inside it.

    :param path: an absolute path.
    :returns: the path, with forward slashes.
    """
    return path.relative_to(REPO).as_posix() if path.is_relative_to(REPO) else path.as_posix()


def load_results(folder):
    """Read every results file in a folder, oldest run first.

    :param folder: the results folder (docs/performance/results).
    :returns: a list of `(stem, doc)` pairs, ordered by each run's start and then its file name.
    :raises SystemExit: when there are no results files, or one can't be read or has another schemaVersion.
    """
    files = sorted(folder.glob("*.json")) if folder.is_dir() else []
    if not files:
        die(f"No results files in {rel(folder)}/, so there is nothing to report. Record a run first, for example:\n"
            f"  {BENCH} --cli local --umbraco 17\nNothing was written.")
    runs = []
    for path in files:
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as e:
            die(f"Can't read {rel(path)}: {e}. Nothing was written.")
        if not isinstance(doc, dict) or doc.get("schemaVersion") != SCHEMA_VERSION:
            found = doc.get("schemaVersion") if isinstance(doc, dict) else None
            die(f"{rel(path)} has schemaVersion {found!r}, and this report reads {SCHEMA_VERSION} only. Update "
                "tests/hands-on/tools/perf_report.py for the new schema. Nothing was written.")
        runs.append((path.stem, doc))
    return sorted(runs, key=lambda run: (run[1]["date"], run[0]))


# ---------------------------------------------------------------- builds -----
def is_local(cli):
    """Whether a result's CLI build was packed from a checkout (`--cli local`) rather than published.

    :param cli: a results row's `cli`.
    :returns: True for a local build.
    """
    return cli["label"] == "local"


def build_key(cli):
    """Sort key for CLI builds: published builds in version order, then local builds by the pack time in their version.

    :param cli: a results row's `cli`.
    :returns: a tuple that orders builds.
    """
    return is_local(cli), harness.version_key(cli["version"])


def build_name(cli):
    """A CLI build as the tables name it: its version, or `local <commit>` for a build of a checkout.

    :param cli: a results row's `cli`.
    :returns: the name.
    """
    return f"local {cli.get('commit') or ''}".rstrip() if is_local(cli) else cli["version"]


def major(version):
    """The major of an Umbraco version.

    :param version: an exact version such as "17.7.0".
    :returns: the major, e.g. "17".
    """
    return version.split(".")[0]


def headline(doc):
    """Choose what the README quotes from one results document.

    That is the document's newest Umbraco version with a successful result and, on that version, its newest
    published CLI build; a local build only when no published build succeeded on it.

    :param doc: the results document.
    :returns: `(Umbraco version, the build's cli, {scenario: row})`, the rows including failed ones.
    :raises SystemExit: when the document has no successful result at all.
    """
    ok = [r for r in doc["results"] if r["status"] == "ok"]
    if not ok:
        die(f"The newest results file ({doc['date']}) has no successful result, so the README has nothing to "
            "quote. Nothing was written.")
    umbraco = max((r["umbraco"] for r in ok), key=harness.version_key)
    on_it = [r["cli"] for r in ok if r["umbraco"] == umbraco]
    cli = max([c for c in on_it if not is_local(c)] or on_it, key=build_key)
    rows = {r["scenario"]: r for r in doc["results"] if r["umbraco"] == umbraco and r["cli"]["version"] == cli["version"]}
    return umbraco, cli, rows


# ---------------------------------------------------------------- text -------
def ms(value):
    """A millisecond value for a table.

    :param value: milliseconds, or None.
    :returns: one decimal, or "n/a".
    """
    return "n/a" if value is None else f"{value:.1f}"


def timing(row):
    """A result's four numeric cells.

    :param row: a results row.
    :returns: end-to-end mean +/- sd, HTTP ms, CLI overhead ms and requests; for a failed row, why and three blanks.
    """
    if row["status"] != "ok":
        error = " ".join((row.get("error") or "no error recorded").split())
        return [f"failed: {error if len(error) <= 80 else error[:77] + '...'}", "", "", ""]
    e2e = row["endToEndMs"]
    return [f"{ms(e2e['mean'])} +/- {ms(e2e['stddev'])}", ms(row["httpMs"]), ms(row["cliOverheadMs"]),
            str(row["requests"])]


def display_command(command):
    """A command as the docs show it, for reading rather than pasting.

    Drops the options every API scenario passes for isolation (`--output json --config {config}`), shows the
    scratch output file as `<file>` and the fixtures folder as its repository path, and any other placeholder
    (a fixture id such as `{home}`) as `<home>`.

    :param command: a results row's `command`, or a scenario's argv joined after `umbraco`.
    :returns: the command.
    """
    text = re.sub(r"\s--output\s+json\b|\s--config\s+\{config\}", "", command)
    text = re.sub(r"\{work\}/\S+", "<file>", text).replace("{fixtures}", "tests/hands-on/fixtures")
    return re.sub(r"\{(\w+)\}", r"<\1>", text)


def run_link(stem, doc):
    """A run as docs/performance.md links it.

    :param stem: the results file name without its extension.
    :param doc: its results document.
    :returns: the run's start (UTC, to the minute, with no space so it never wraps) linking to its results file.
    """
    return f"[{doc['date'][:16]}Z](performance/results/{stem}.json)"


def link(number, kind="issues"):
    """A link to a GitHub issue or pull request (a repository file doesn't autolink `#123`).

    :param number: the issue or PR number.
    :param kind: "issues" or "pull".
    :returns: the markdown link.
    """
    return f"[#{number}]({GITHUB}/{kind}/{number})"


# ---------------------------------------------------------------- markdown ---
def para(text, indent=""):
    """One paragraph of prose, wrapped at WIDTH.

    A wrapped line never starts with something markdown would read as a list item, quote, table or heading:
    such a line is joined to the one before it instead.

    :param text: the paragraph, with any spacing.
    :param indent: the first line's prefix (a list marker such as "- "); later lines get as many spaces.
    :returns: the wrapped paragraph.
    """
    lines = textwrap.wrap(" ".join(text.split()), WIDTH, initial_indent=indent, subsequent_indent=" " * len(indent),
                          break_long_words=False, break_on_hyphens=False)
    out = lines[:1]
    for line in lines[1:]:
        if BLOCK_START.match(line.strip()):
            out[-1] += " " + line.strip()
        else:
            out.append(line)
    return "\n".join(out)


def bullets(*items):
    """A bulleted list of prose items (each wrapped as `para` wraps).

    :param items: the items' text.
    :returns: the list.
    """
    return "\n".join(para(item, "- ") for item in items)


def table(headers, align, rows):
    """A markdown table.

    :param headers: the column headings.
    :param align: "l" or "r" per column.
    :param rows: lists of cell text. A `|` or line break in a cell is replaced, so the cell stays one cell.
    :returns: the table.
    """
    def cell(text):
        return " ".join(str(text).split()).replace("|", "/")
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" if a == "l" else "--:" for a in align) + "|"]
    return "\n".join(lines + ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows])


def code(text):
    """A fenced bash block.

    :param text: the commands.
    :returns: the block.
    """
    return f"```bash\n{text}\n```"


def ascii_only(text):
    """Text with only ASCII characters: known punctuation spelled out, accents dropped, anything else as "?".

    :param text: the generated markdown.
    :returns: the same text in ASCII.
    """
    text = unicodedata.normalize("NFKD", "".join(ASCII.get(c, c) for c in text))
    return "".join(c for c in text if not unicodedata.combining(c)).encode("ascii", "replace").decode("ascii")


RESULT_HEADERS = ["End-to-end ms (mean +/- sd)", "HTTP ms", "CLI overhead ms", "Requests"]


# ---------------------------------------------------------------- README -----
def readme_block(doc):
    """The README's Performance section: the headline table from one results document, and its stamp.

    :param doc: the newest results document.
    :returns: the markdown that goes between the markers.
    """
    umbraco, cli, rows = headline(doc)
    body = []
    for scenario, what in HEADLINE:
        row = rows.get(scenario)
        if row is None:
            body.append([what, "not measured in this run", "", ""])
        elif row["status"] != "ok":
            body.append([f"{what}: `{display_command(row['command'])}`", "failed (see docs/performance.md)", "", ""])
        else:
            e2e, _, overhead, requests = timing(row)
            body.append([f"{what}: `{display_command(row['command'])}`", e2e, overhead, requests])

    m, h = doc["machine"], doc["hyperfine"]
    build = cli["version"] + (f", commit {cli['commit']}" if cli.get("commit") else "")
    note = f" Note on this run: {doc['note']}" if doc.get("note") else ""
    return "\n\n".join([
        GENERATED.format(what="between the perf markers"),
        "## Performance",
        para("The CLI wraps Umbraco's Management API, so most of a command's time is Umbraco's; the CLI's own "
             "share is shown separately. CI gates request counts and allocations, never timings."),
        table(["Command", "End-to-end ms, including Umbraco server time", "CLI overhead ms", "HTTP requests"],
              "lrrr", body),
        para(f"Measured {doc['date'][:10]} on {m['cpu']}, {m['logicalCores']} logical cores, {m['os']}: CLI {build} "
             f"(.NET {cli.get('dotnet') or 'unknown'}) against Umbraco {umbraco} on the same machine (the test "
             f"harness's dev site). Mean +/- standard deviation of {h['runs']} hyperfine runs. CLI overhead is "
             "end-to-end minus the time in HTTP requests: startup, auth, parsing, the CLI's own work and output."
             f"{note}"),
        para("Method, history across CLI versions, caveats and how to reproduce every number: "
             "[docs/performance.md](docs/performance.md)."),
    ])


# ---------------------------------------------------------------- page -------
def method_section(scenarios):
    """The page's Method section: the three layers, what each catches, the scenarios, and why timings don't gate.

    :param scenarios: bench.py's SCENARIOS.
    :returns: the markdown.
    """
    counts, bdn = "../tests/Umbraco.Cli.Tests/RequestCounts/", "../tests/Umbraco.Cli.Benchmarks/README.md"
    workflow = f"{GITHUB}/actions/workflows/benchmarks.yml"
    return "\n\n".join([
        "## Method",
        para("Three layers measure the CLI, each where it can measure reliably. Only the two deterministic ones "
             "can fail a build."),
        table(["Layer", "Measures", "Runs", "Can fail a build?"], "llll", [
            [f"[Request counts]({counts})", "HTTP requests per command, and token requests per run, against a fake "
             "Umbraco that records every request", "`dotnet test`, on every pull request", "Yes: exact counts"],
            [f"[BenchmarkDotNet]({bdn})", "CPU time and allocated bytes of code the CLI owns, on in-memory fixtures",
             "CI: pull requests labelled `performance`, weekly on `main`, on demand",
             "Allocations: yes, more than 10% over `main`. Timings: no"],
            ["[hyperfine](../tests/hands-on/README.md#benchmarks-benchpy)", "End-to-end time, HTTP time and CLI "
             "overhead, per CLI build and Umbraco version", "Locally, against the test harness's dev site",
             "No: it reports"],
        ]),
        "### Request counts",
        para(f"The request-count tests ([`tests/Umbraco.Cli.Tests/RequestCounts/`]({counts})) run the shipped command "
             "tree, client and authentication end to end, with only the transport replaced: a fake Umbraco answers "
             "and records every request, the token exchange included. Each test pins how many requests a command "
             "makes, as a formula over the fixture's size where the count depends on it (for example "
             "`ceil(n / 100)` tree pages for `content tree` with n items at the root)."),
        bullets("**Catches:** a change that turns one request into one per item, a lost cache (a type read for "
                "every row, a token exchange for every request), and paging that asks for more pages than it "
                "needs. A failure names the command line, the expected and actual counts, the formula and every "
                "request sent.",
                "**Can't catch:** how long a request takes, the CLI's own CPU and allocations, or anything the real "
                "Umbraco does differently from the fake."),
        "### BenchmarkDotNet allocation gate",
        para(f"[`tests/Umbraco.Cli.Benchmarks`]({bdn}) measures startup wiring, the output writers, Kiota response "
             "parsing, and the content and schema snapshot and diff engines, on deterministic in-memory fixtures, "
             f"so no Umbraco is involved. The [Benchmarks workflow]({workflow}) "
             "([`benchmarks.yml`](../.github/workflows/benchmarks.yml)) runs the pull request and `main` on the "
             "same runner and fails when a benchmark's allocated bytes per operation rise more than 10% over "
             "`main`."),
        bullets("**Catches:** an extra copy per item, a lost buffer reuse, or other new work per item that "
                "allocates, in code the CLI owns.",
                "**Can't catch:** network or server time, the number of requests, or (as a gate) CPU time: timings "
                "are in the job summary, but they don't fail the build."),
        para("Its results are not committed, so they are not on this page. Each run uploads its JSON reports as "
             f"the `benchmark-results` artifact (kept 90 days) of the [Benchmarks workflow]({workflow}), and the "
             "job summary shows the pull request against `main`."),
        "### hyperfine end to end",
        para("[`tests/hands-on/bench.py`](../tests/hands-on/README.md#benchmarks-benchpy) times real commands with "
             "[hyperfine](https://github.com/sharkdp/hyperfine) against the test harness's dev site: a local Umbraco "
             "with the harness's fixture content, rebuilt for each Umbraco version so every run times the same "
             "content. Each CLI build is installed side by side and run through its `umbraco` shim, as an installed "
             "tool runs. hyperfine gives the end-to-end time (warm-up runs, then timed runs, with no shell and the "
             "output discarded). Separate `--verbose` runs, which hyperfine never times, give the HTTP time: the "
             "CLI logs each response's duration, and the HTTP time is the length of the union of those intervals, "
             "so concurrent requests count once. CLI overhead is the end-to-end time minus the HTTP time. The "
             "results are committed to [`docs/performance/results/`](performance/results/), and they are the only "
             "numbers on this page."),
        bullets("**Catches:** what a user waits for, per CLI build and Umbraco version, and whether a change in "
                "that time is the CLI's (CLI overhead) or the server's (HTTP time).",
                "**Can't catch:** small regressions, reliably: it runs on one machine against a local site, and "
                "other load on the machine moves the numbers. It doesn't run in CI."),
        para("The scenarios (the `SCENARIOS` table in `bench.py`):"),
        table(["Scenario", "Command", "What it exercises"], "lll",
              [[f"`{s.name}`", f"`{display_command(' '.join(['umbraco', *s.argv]))}`", s.about] for s in scenarios]),
        "### Why timings never gate CI",
        bullets(f"CI has no live Umbraco instance, by decision ({link(139)}, {link(77)}), so end-to-end timing can't "
                "run there, and a run on one developer's machine can't gate anyone else's pull request.",
                "Timings on shared CI runners move between identical runs by more than the regressions worth "
                "catching. A threshold tight enough to catch one would fail at random; one loose enough not to "
                "would catch nothing.",
                "The likely regressions show up deterministically anyway: request fan-out as a higher request "
                "count, and extra work per item as more allocated bytes. So the gates are on counts and bytes, and "
                "timings are reported for people to read."),
    ])


def history_section(runs, scenario_key):
    """The page's History section: every run, the machines, and one table per scenario across CLI builds.

    :param runs: every `(stem, doc)`, oldest first.
    :param scenario_key: sort key for scenario names (bench.py's order first).
    :returns: the markdown.
    """
    run_rows, machines = [], {}
    for stem, doc in runs:
        rows, h = doc["results"], doc["hyperfine"]
        builds = sorted({r["cli"]["version"]: r["cli"] for r in rows}.values(), key=build_key)
        run_rows.append([run_link(stem, doc), doc["machine"]["label"], ", ".join(dict.fromkeys(r["umbraco"] for r in rows)),
                         ", ".join(build_name(c) for c in builds),
                         f"{h['version']}: {h['warmup']} warm-up + {h['runs']} timed runs; {doc['httpRuns']} HTTP runs",
                         doc.get("note") or ""])
        machines[doc["machine"]["label"]] = doc["machine"]  # the newest file's details win

    parts = [
        "## History across CLI versions",
        para("Every committed run, oldest first. The times are UTC, and each run links to its results file."),
        table(["Run", "Machine", "Umbraco", "CLI builds", "hyperfine", "Note"], "llllll", run_rows),
        para("The machines:"),
        table(["Machine", "CPU", "Logical cores", "RAM GiB", "OS", "Arch"], "llrrll",
              [[label, m["cpu"], str(m["logicalCores"]), "n/a" if m.get("memoryGiB") is None else str(m["memoryGiB"]),
                m["os"], m["arch"]] for label, m in sorted(machines.items())]),
        para("Each scenario below has one row per CLI build and run, published builds in version order and then "
             "local builds. End-to-end times include Umbraco's server time; CLI overhead is end-to-end minus HTTP "
             "time. Compare rows from the same machine only."),
    ]
    results = [(stem, doc, r) for stem, doc in runs for r in doc["results"]]
    for name in sorted({r["scenario"] for _, _, r in results}, key=scenario_key):
        mine = sorted((x for x in results if x[2]["scenario"] == name),
                      key=lambda x: (build_key(x[2]["cli"]), x[1]["date"], x[0], harness.version_key(x[2]["umbraco"])))
        commands = dict.fromkeys(f"`{display_command(r['command'])}`" for _, _, r in mine)
        parts += [f"### `{name}`", para(f"Command: {'; '.join(commands)}"),
                  table(["CLI", "Umbraco", "Run", "Machine", *RESULT_HEADERS], "llllrrrr",
                        [[build_name(r["cli"]), r["umbraco"], run_link(stem, doc), doc["machine"]["label"], *timing(r)]
                         for stem, doc, r in mine])]
    return "\n\n".join(parts)


def umbraco_section(runs, scenario_key):
    """The page's Umbraco comparison: the same build and scenario on more than one Umbraco major, on one machine.

    Takes the newest result for each machine, scenario, CLI build and exact Umbraco version, and shows the groups
    (machine, scenario, build) that cover more than one major. When there are none, it says "Not yet measured".

    :param runs: every `(stem, doc)`, oldest first.
    :param scenario_key: sort key for scenario names.
    :returns: the markdown.
    """
    newest = {}
    for stem, doc in runs:  # oldest first, so a newer run replaces an older one
        for r in doc["results"]:
            newest[(doc["machine"]["label"], r["scenario"], r["cli"]["version"], r["umbraco"])] = (stem, doc, r)
    groups = {}
    for (machine, scenario, version, _), found in newest.items():
        groups.setdefault((machine, scenario, version), []).append(found)
    compared = [found for group in groups.values() if len({major(r["umbraco"]) for _, _, r in group}) > 1
                for found in group]
    measured = sorted({r["umbraco"] for _, doc in runs for r in doc["results"]}, key=harness.version_key)
    majors = sorted({major(v) for v in measured}, key=harness.version_key)
    # With one major so far, suggest it and the next one; otherwise every major there are results for.
    wanted = majors if len(majors) > 1 else majors + [str(int(majors[0]) + 1)]
    how = code(f"{BENCH} --cli local --umbraco {','.join(wanted)}")

    parts = ["## Umbraco versions"]
    if not compared:
        if len(majors) > 1:
            said = (f"Results exist for Umbraco {', '.join(majors)}, but no machine has run the same CLI build on "
                    "more than one of them, so they can't be compared yet.")
        else:
            said = (f"Every result so far is on Umbraco {majors[0]} ({', '.join(measured)}). Once a run covers "
                    "another major, this section compares them.")
        return "\n\n".join(parts + [para(f"Not yet measured. {said} To measure it, run each version in one run on "
                                         "one machine:"), how])
    compared.sort(key=lambda x: (x[1]["machine"]["label"], scenario_key(x[2]["scenario"]), build_key(x[2]["cli"]),
                                 harness.version_key(x[2]["umbraco"])))
    return "\n\n".join(parts + [
        para("The same CLI build and scenario on more than one Umbraco major, on the same machine, from the newest "
             "run of each. HTTP time is where a change in Umbraco shows; the CLI overhead of one build should barely "
             "move between Umbraco versions. When the versions come from different runs, anything else that "
             "changed between those runs (load on the machine, an update) is in the difference too."),
        table(["Scenario", "CLI", "Umbraco", "Run", "Machine", *RESULT_HEADERS], "lllllrrrr",
              [[f"`{r['scenario']}`", build_name(r["cli"]), r["umbraco"], run_link(stem, doc), doc["machine"]["label"],
                *timing(r)] for stem, doc, r in compared]),
    ])


def rerun_command(doc, scenario_names):
    """The bench.py command that repeats a run: its builds, Umbraco versions, scenarios and hyperfine settings.

    :param doc: the run's results document.
    :param scenario_names: bench.py's scenario names; `--scenario` is added only when the run timed a subset.
    :returns: the command line.
    """
    rows, h = doc["results"], doc["hyperfine"]
    clis = dict.fromkeys("local" if is_local(r["cli"]) else r["cli"]["version"] for r in rows)
    cmd = [BENCH, "--cli", ",".join(clis), "--umbraco", ",".join(dict.fromkeys(r["umbraco"] for r in rows))]
    timed = list(dict.fromkeys(r["scenario"] for r in rows))
    if set(timed) != set(scenario_names):
        cmd += ["--scenario", ",".join(timed)]
    return " ".join(cmd + ["--warmup", str(h["warmup"]), "--runs", str(h["runs"]), "--http-runs", str(doc["httpRuns"])])


def reproduce_section(runs, scenario_names):
    """The page's Reproduce section: exact commands for each layer, each committed run, and this page.

    :param runs: every `(stem, doc)`, oldest first.
    :param scenario_names: bench.py's scenario names.
    :returns: the markdown.
    """
    bdn = 'dotnet run -c Release --project tests/Umbraco.Cli.Benchmarks -- --filter "*" --job short'
    parts = [
        "## Reproduce",
        para("Every command runs from the repository root. On Windows, type `python` for `python3`."),
        "### Request counts",
        code('dotnet test tests/Umbraco.Cli.Tests --filter "FullyQualifiedName~RequestCount"'),
        para("They need no Umbraco, and they also run in every `dotnet test`."),
        "### BenchmarkDotNet",
        code(bdn),
        para("This is the job CI runs. To compare two builds the way the gate does:"),
        code(f"{bdn} --artifacts ./bench/before\n# ...make the change...\n{bdn} --artifacts ./bench/after\n"
             "pwsh ./scripts/ci/benchmark-compare.ps1 -Baseline ./bench/before -Candidate ./bench/after "
             "-BaselineLabel before -CandidateLabel after"),
        para("See [its README](../tests/Umbraco.Cli.Benchmarks/README.md) for running one class or benchmark."),
        "### The hyperfine runs on this page",
        para("These need the [test harness's requirements](../tests/hands-on/README.md#requirements) and hyperfine. "
             "Each command repeats one committed run, and writes a new results file to compare with it. A "
             "published build that isn't on nuget.org (a release that was packed but not pushed) installs from "
             "`./nupkg` or from `--source <folder>`. Add `--note \"<text>\"` to record anything unusual about the "
             "run, such as other load on the machine."),
    ]
    for stem, doc in runs:
        commits = dict.fromkeys(r["cli"]["commit"] for r in doc["results"] if is_local(r["cli"]) and r["cli"]["commit"])
        checkout = ""
        for commit in commits:
            if commit.endswith("-dirty"):
                checkout += (f" Its `local` build was commit {commit[:-6]} with uncommitted changes in `src/`, so it "
                             "can't be rebuilt exactly.")
            else:
                checkout += f" Its `local` build was commit {commit}: run `git checkout {commit}` first."
        parts += [para(f"{run_link(stem, doc)} on {doc['machine']['label']}.{checkout}"), code(rerun_command(doc, scenario_names))]
    parts += [
        "### This page and the README section",
        code(f"{BENCH} report"),
        para("It reads every file in `docs/performance/results/`, rewrites this page, and rewrites only the block "
             "between `<!-- perf:start -->` and `<!-- perf:end -->` in `README.md`. Running it again without new "
             "results changes nothing. Commit a new results file and the regenerated pages together."),
    ]
    return "\n\n".join(parts)


def caveats_section(runs):
    """The page's Caveats section: noise (with each run's note), and what the HTTP and overhead split can't see.

    :param runs: every `(stem, doc)`, oldest first.
    :returns: the markdown.
    """
    noted = [f"{run_link(stem, doc)}: {doc['note']}" for stem, doc in runs if doc.get("note")]
    noise = ("**Noise.** Each number comes from one run on one machine. hyperfine's standard deviation is the "
             "spread to compare against: a difference smaller than the two results' spreads added together is "
             "noise. Other load on the machine (builds, test runs, other benchmarks) widens the spread and moves "
             "the means, so a run meant for committing should be on a quiet machine, and a run that wasn't says so "
             "in its note." + (" Runs with a note:" if noted else " No run has a note so far."))
    others = bullets(
        "**End-to-end includes Umbraco.** It is what a user waits for: the CLI plus Umbraco's server time, here on "
        "a local site with the harness's small fixture content. A real site, a remote host or another Umbraco "
        "version moves it. Compare CLI overhead across CLI builds, and HTTP time across Umbraco versions.",
        "**HTTP time is more than server time.** It is everything inside the HTTP stack. In particular, the first "
        "request of each process opens the connection (TCP and the TLS handshake) and pays for the first use of "
        ".NET's HTTP stack, so a command that makes any request has some HTTP time even when Umbraco answers "
        "at once.",
        "**CLI overhead includes reading response bodies.** The CLI's clock for a request stops at the response "
        "headers, so reading the body counts as CLI overhead. On localhost that part is small.",
        "**Only requests a build logs are counted.** Builds before 0.1.0-alpha.15 don't log the OAuth token "
        "exchange under `--verbose`, and builds before 0.1.0-alpha.14 have no token cache, so they exchange a token "
        "on every run. For those builds (such as 0.1.0-alpha.6) the token round trip is in CLI overhead, and it is "
        "missing from their request counts.",
        "**Logged durations are whole milliseconds,** truncated, so bench.py adds half a millisecond to each.",
        "**Builds do different work.** A later build's command can make more requests than an earlier one's (more "
        "follow-up reads, for a fuller result), so compare the request counts before the times. A failed row is a "
        "build without that command or snapshot format, not a slow one.",
        "**Machines differ.** Numbers from different machines aren't comparable. Compare rows from the same "
        "machine.",
    )
    # One list, so it renders tight: the noise item, the runs' notes nested under it, then the other items.
    return "\n\n".join(["## Caveats", "\n".join([bullets(noise), *(para(n, "  - ") for n in noted), others])])


def render_page(runs, scenarios):
    """docs/performance.md, whole.

    :param runs: every `(stem, doc)`, oldest first.
    :param scenarios: bench.py's SCENARIOS.
    :returns: the markdown.
    """
    order = {s.name: i for i, s in enumerate(scenarios)}

    def scenario_key(name):
        return order.get(name, len(order)), name
    stem, doc = runs[-1]
    umbraco, cli, _ = headline(doc)
    return "\n\n".join([
        "# Performance",
        GENERATED.format(what="this file"),
        para("How fast the `umbraco` CLI is, how that is measured, and how to reproduce every number here. The CLI "
             "wraps Umbraco's Management API, so most of a command's wall time is spent in Umbraco. The parts the "
             "CLI owns are process startup, config and authentication, how many requests a command makes, and its "
             "own CPU: parsing, writing output, and the export, diff and apply engines."),
        para(f"The [README](../README.md#performance) quotes CLI {build_name(cli)} on Umbraco {umbraco} from the run "
             f"of {run_link(stem, doc)}. Every run is under "
             "[History across CLI versions](#history-across-cli-versions)."),
        method_section(scenarios),
        history_section(runs, scenario_key),
        umbraco_section(runs, scenario_key),
        reproduce_section(runs, [s.name for s in scenarios]),
        caveats_section(runs),
    ]) + "\n"


# ---------------------------------------------------------------- output -----
def read_raw(path):
    """A file's text exactly as it is on disk, line endings included.

    :param path: the file.
    :returns: the text, or None when there is no file.
    """
    if not path.is_file():
        return None
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def replace_block(text, block):
    """README.md's text with the block between the markers replaced, and nothing else changed.

    Works on the text as it is on disk, so every byte outside the block, line endings included, stays as it was;
    the block takes the file's line endings.

    :param text: README.md as `read_raw` returns it.
    :param block: the new block, with "\\n" line endings.
    :returns: the new text.
    :raises SystemExit: when there is no README.md, or it doesn't hold exactly one start marker followed by one
        end marker.
    """
    if text is None:
        die(f"{rel(README)} is missing. Nothing was written.")
    starts, ends = text.count(START), text.count(END)
    if starts != 1 or ends != 1 or text.index(START) > text.index(END):
        found = "the end marker comes first" if starts == ends == 1 else f"found {starts} start and {ends} end markers"
        die(f"{rel(README)} must hold one {START} line and, after it, one {END} line, around the Performance "
            f"section ({found}). Put the two lines where the section goes, then run this again. Nothing was written.")
    newline = "\r\n" if "\r\n" in text else "\n"
    head, rest = text.split(START, 1)
    return head + START + newline + block.replace("\n", newline) + newline + END + rest.split(END, 1)[1]


def write(path, old, new):
    """Write a file only when its text changes.

    :param path: the file.
    :param old: its current text (None when it doesn't exist).
    :param new: the text it should have.
    :returns: whether the file was written.
    """
    if old == new:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(new)
    return True


def main(argv, scenarios):
    """Regenerate the README's Performance block and docs/performance.md (`bench.py report`).

    :param argv: the arguments after `report`.
    :param scenarios: bench.py's SCENARIOS: the scenario order, and the table of what each one runs.
    :raises SystemExit: as the module docstring says, before anything is written.
    """
    argparse.ArgumentParser(prog="bench.py report", description=__doc__,
                            formatter_class=argparse.RawDescriptionHelpFormatter).parse_args(argv)
    runs = load_results(RESULTS)
    stem, doc = runs[-1]

    # ---- render both, and check the README's markers, before writing either --------
    old_readme = read_raw(README)
    new_readme = replace_block(old_readme, ascii_only(readme_block(doc)))
    old_page = read_raw(PAGE)
    newline = "\r\n" if old_page and "\r\n" in old_page else "\n"  # keep the checkout's line endings
    new_page = ascii_only(render_page(runs, scenarios)).replace("\n", newline)

    for path, old, new in ((README, old_readme, new_readme), (PAGE, old_page, new_page)):
        say(f"{rel(path)}: {'updated' if write(path, old, new) else 'unchanged'}")
    umbraco, cli, _ = headline(doc)
    print(f"    from {len(runs)} results file(s); the README quotes CLI {build_name(cli)} on Umbraco {umbraco} "
          f"from {stem}")
